#!/bin/bash

set -e

BID=$1

# expected output files - touch so that job does not go into
# hold on failures
touch $BID-DL.json

(
    # Wait for lock on .untarlock (fd 200) for 15 minutes
    flock -x -w 900 200

    # extract the data tarball unless it has already been done
    if [ ! -e data/ATCCurves ]; then
        tar xzf DL-data.tar.gz
    fi
) 200>.untarlock

chmod 755 createLOSS
./createLOSS $BID-BIM.json $BID-EDP.json $BID-DL.json

