#!/bin/bash

set -e
set -v

BID=$1

ls -l

# make sure HazusData.txt is where we expect it
mkdir -p data
cp HazusData.txt data/

chmod 755 createSAM
./createSAM $BID-BIM.json $BID-EVENT.json $BID-SAM.json

